# conda environment for $0 named pipeline; create using:
# conda env create -f $0
name: exome_n-of-1-1.0
channels:
  - conda-forge
  - bioconda
  - defaults
  - pcgr
dependencies:
  - bbmap=38.57-0
  - fastp=0.20.0-0
  - fastqc=0.11.8
  - bwa=0.7.17
  - samtools=1.9
  - picard=2.20.3-0
  - gatk4=4.1.2.0
  - pcgr::pcgr=0.8.1.3
  - r-facets=0.5.14-1
  - msisensor=0.5-0
  - manta=1.5.0-0
  - strelka=2.9.10-0
  - vep=92.4
  - bioconductor-ensemblvep=1.24.0-0
  - bioconductor-org.hs.eg.db=3.7.0-0
  - bioconductor-customprodb=1.22.0-0
  - bioconductor-genomicranges=1.34.0-0
  - conda-forge::r-data.table=1.12.0
  - conda-forge::r-tidyverse=1.2.1
  - conda-forge::r-pheatmap=1.0.12
  - conda-forge::r-plyr=1.8.4
  - conda-forge::r-biocmanager=1.30.4
  - conda-forge::perl=5.26.2
