# conda environment for $0 named pipeline; create using:
# conda env create -f $0
name: exome_n-of-1-1.0
channels:
  - conda-forge
  - bioconda
  - defaults
  - pcgr
dependencies:
  - bbmap=38.57
  - fastp=0.20.0
  - conda-forge::openjdk=8.0.144
  - anaconda::font-ttf-dejavu-sans-mono=2.37
  - fontconfig=2.12.6
  - fastqc=0.11.8
  - bwa=0.7.17
  - samtools=1.9
  - picard=2.20.3
  - gatk4=4.1.2.0
  - msisensor=0.5
  - manta=1.5.0-0
  - multiqc=1.7
  - strelka=2.9.10
  - ensembl-vep=96.0
  - conda-forge::perl
