name: somatic_exome_n-of-1
channels:
  - anaconda
  - conda-forge
  - r
  - pcgr
  - bioconda
  - defaults
dependencies:
  - ascat=2.5.1
  - bbmap=38.57
  - bcftools=1.9
  - bedtools=2.28.0
  - bioconductor-biomart
  - bioconductor-bsgenome
  - bioconductor-bsgenome.hsapiens.ucsc.hg38
  - bioconductor-ensembldb
  - bioconductor-ensemblvep
  - bioconductor-purecn
  - bioconductor-qdnaseq
  - bwa=0.7.17
  - cancerit-allelecount=4.0.2
  - crcmod=1.7
  - ensembl-vep=97.0
  - fastp=0.20.0
  - fastqc=0.11.8
  - gatk4=4.1.2.0
  - htslib=1.9
  - libiconv=1.15
  - msisensor=0.5
  - multiqc=1.7
  - octopus=0.5.2b
  - pcgr=0.8.2.2
  - perl=5.26.2
  - picard=2.20.3=0
  - pisces=5.2.9.122
  - r-facets=0.5.14
  - r-sequenza=2.1.2
  - samtools=1.9
  - snp-pileup=0.5.14
  - ucsc-liftover=377
  - varlociraptor=1.5.0
